inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'ofx.gemspec'
